export const EOD_CONFIG=Object.freeze({minDailyCandles:120,rsiPeriod:14,volumePeriod:20,volumeMultiplier:1.5,longCandlePct:3,explosionPct:6,pivotWindow:2,atrPeriod:14,maxStopPct:4,stopBufferPct:.35,minScore:70,fibTolerancePct:.7,zoneTolerancePct:1,recentWindow:12,explosionSequence:3});
const avg=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:0;
const pct=(a,b)=>b?(a-b)/b*100:0;
const bodyPct=c=>Math.abs(pct(c.close,c.open));
const green=c=>c.close>c.open,red=c=>c.close<c.open;
const valid=c=>c&&c.date&&['open','high','low','close','volume'].every(k=>Number.isFinite(Number(c[k])));
const near=(price,level,tolerance=1)=>Number.isFinite(level)&&Math.abs(price-level)/price*100<=tolerance;

export function normalizeCandles(rows,preserveTime=false){const unique=new Map();for(const row of rows||[]){const raw=String(row.date||row.time||''),date=preserveTime?raw:raw.slice(0,10),c={date,open:+row.open,high:+row.high,low:+row.low,close:+row.close,volume:+(row.volume??row.Volume)};if(valid(c))unique.set(c.date,c)}return[...unique.values()].sort((a,b)=>a.date.localeCompare(b.date))}
export function aggregate(candles,period){const groups=new Map();for(const c of candles){const d=new Date(`${c.date}T12:00:00Z`);let key;if(period==='month')key=c.date.slice(0,7);else{const day=d.getUTCDay(),th=new Date(d);th.setUTCDate(d.getUTCDate()+(4-day+7)%7);key=th.toISOString().slice(0,10)}if(!groups.has(key))groups.set(key,[]);groups.get(key).push(c)}return[...groups.entries()].map(([date,a])=>({date,open:a[0].open,high:Math.max(...a.map(x=>x.high)),low:Math.min(...a.map(x=>x.low)),close:a.at(-1).close,volume:a.reduce((s,x)=>s+x.volume,0)}))}
function rsiSeries(cs,n=14){const out=Array(cs.length).fill(null);if(cs.length<=n)return out;let g=0,l=0;for(let i=1;i<=n;i++){const d=cs[i].close-cs[i-1].close;g+=Math.max(d,0);l+=Math.max(-d,0)}let ag=g/n,al=l/n;out[n]=al?100-100/(1+ag/al):100;for(let i=n+1;i<cs.length;i++){const d=cs[i].close-cs[i-1].close;ag=(ag*(n-1)+Math.max(d,0))/n;al=(al*(n-1)+Math.max(-d,0))/n;out[i]=al?100-100/(1+ag/al):100}return out}
function atr(cs,n=14){const tr=cs.map((c,i)=>i?Math.max(c.high-c.low,Math.abs(c.high-cs[i-1].close),Math.abs(c.low-cs[i-1].close)):c.high-c.low);return avg(tr.slice(-n))}
function pivots(cs,w=2){const highs=[],lows=[];for(let i=w;i<cs.length-w;i++){const a=cs.slice(i-w,i+w+1);if(cs[i].high===Math.max(...a.map(x=>x.high)))highs.push(i);if(cs[i].low===Math.min(...a.map(x=>x.low)))lows.push(i)}return{highs,lows}}
function trendOf(cs,w=2){const p=pivots(cs,w),h=p.highs.slice(-2),l=p.lows.slice(-2);if(h.length<2||l.length<2)return'neutral';if(cs[h[1]].high>cs[h[0]].high&&cs[l[1]].low>cs[l[0]].low)return'up';if(cs[h[1]].high<cs[h[0]].high&&cs[l[1]].low<cs[l[0]].low)return'down';return'neutral'}
function divergences(cs,n,w){const rsi=rsiSeries(cs,n),p=pivots(cs,w),L=p.lows.slice(-2),H=p.highs.slice(-2),ok=a=>a.length===2&&rsi[a[0]]!=null&&rsi[a[1]]!=null;return{bullishRegular:ok(L)&&cs[L[1]].low<cs[L[0]].low&&rsi[L[1]]>rsi[L[0]],bullishHidden:ok(L)&&cs[L[1]].low>cs[L[0]].low&&rsi[L[1]]<rsi[L[0]],bearishRegular:ok(H)&&cs[H[1]].high>cs[H[0]].high&&rsi[H[1]]<rsi[H[0]],bearishHidden:ok(H)&&cs[H[1]].high<cs[H[0]].high&&rsi[H[1]]>rsi[H[0]]}}
function fibonacci(cs,last,tolerance,w){const p=pivots(cs,w),pairs=[];if(p.lows.length&&p.highs.length){const li=p.lows.at(-1),hi=p.highs.at(-1);if(li<hi)pairs.push({from:cs[li].low,to:cs[hi].high,direction:'up'});if(hi<li)pairs.push({from:cs[hi].high,to:cs[li].low,direction:'down'})}for(const pair of pairs){const levels=[.382,.5,.618].map(r=>pair.to+(pair.from-pair.to)*r),hit=levels.find(level=>near(last,level,tolerance));if(hit)return{near:true,level:hit,direction:pair.direction}}return{near:false,level:null,direction:null}}
function volumeCandles(cs,c){return cs.map((x,i)=>{const base=avg(cs.slice(Math.max(0,i-c.volumePeriod),i).map(v=>v.volume));return{...x,index:i,highVolume:i>=c.volumePeriod&&base>0&&x.volume>=base*c.volumeMultiplier&&(x.high-x.low)>=atr(cs.slice(0,i+1),c.atrPeriod)*1.1}}).filter(x=>x.highVolume)}
function explosionEvents(cs,c){const events=[];for(let i=1;i<cs.length;i++){let direction=null,start=i;if(bodyPct(cs[i])>=c.explosionPct)direction=green(cs[i])?'up':red(cs[i])?'down':null;if(!direction&&i>=c.explosionSequence-1){const a=cs.slice(i-c.explosionSequence+1,i+1);if(a.every(green)&&pct(a.at(-1).close,a[0].open)>=c.explosionPct){direction='up';start=i-c.explosionSequence+1}if(a.every(red)&&pct(a.at(-1).close,a[0].open)<=-c.explosionPct){direction='down';start=i-c.explosionSequence+1}}if(!direction)continue;let origin=start-1;while(origin>0&&(direction==='up'?green(cs[origin]):red(cs[origin])))origin--;const source=cs[origin]||cs[start],range=cs.slice(start,i+1);events.push({direction,start,end:i,date:cs[start].date,zoneLow:Math.min(source.low,...range.map(x=>x.low)),zoneHigh:Math.max(source.high,...range.map(x=>x.high)),originDate:source.date})}return events}
function latestTrap(cs,p,c){const start=Math.max(2,cs.length-c.recentWindow);let falseBreak=null,falseBreakout=null;for(let i=start;i<cs.length;i++){const priorLow=p.lows.filter(x=>x<i).map(x=>cs[x].low).at(-1),priorHigh=p.highs.filter(x=>x<i).map(x=>cs[x].high).at(-1),x=cs[i];if(Number.isFinite(priorLow)&&x.low<priorLow&&x.close>priorLow)falseBreak={index:i,level:priorLow,confirmed:true};if(Number.isFinite(priorHigh)&&x.high>priorHigh&&x.close<priorHigh)falseBreakout={index:i,level:priorHigh,confirmed:true}}return{falseBreak,falseBreakout}}
function candlePatterns(cs){const mother=cs.at(-3),baby=cs.at(-2),confirm=cs.at(-1),before=cs.slice(-9,-3),priorMove=pct(mother.close,before[0]?.open),inside=Math.max(baby.open,baby.close)<=Math.max(mother.open,mother.close)&&Math.min(baby.open,baby.close)>=Math.min(mother.open,mother.close);return{haramiBull:priorMove<0&&red(mother)&&green(baby)&&inside&&confirm.close>mother.high,haramiBear:priorMove>0&&green(mother)&&red(baby)&&inside&&confirm.close<mother.low,inside}}
function largeContraryTrap(cs,trend,c){for(let i=Math.max(1,cs.length-c.recentWindow);i<cs.length-1;i++){const x=cs[i],after=cs.slice(i+1),long=bodyPct(x)>=c.longCandlePct;if(trend==='up'&&long&&red(x)&&after.some(v=>v.close>x.high))return{buy:true,sell:false,index:i,level:x.high};if(trend==='down'&&long&&green(x)&&after.some(v=>v.close<x.low))return{buy:false,sell:true,index:i,level:x.low}}return{buy:false,sell:false,index:null,level:null}}
function volumeTrap(cs,volumes,trend,c){const recent=volumes.filter(v=>v.index>=cs.length-c.recentWindow-5);for(const v of recent){const after=cs.slice(v.index+1);if(trend==='up'&&after.some(x=>x.low<v.low)&&cs.at(-1).close>v.high)return{buy:true,sell:false,index:v.index};if(trend==='down'&&after.some(x=>x.high>v.high)&&cs.at(-1).close<v.low)return{buy:false,sell:true,index:v.index}}return{buy:false,sell:false,index:null}}
function smallTimeframeEvidence(rows,c,bias){const cs=normalizeCandles(rows,true);if(cs.length<30)return{available:false,buy:false,sell:false,reason:'يلزم 30 شمعة على فاصل الساعة أو أقل لتأكيد نقطة الدخول.'};const p=pivots(cs,c.pivotWindow),t=latestTrap(cs,p,c),pat=candlePatterns(cs),last=cs.at(-1),prev=cs.at(-2),buy=Boolean(t.falseBreak||pat.haramiBull||(last.close>prev.high&&green(last))),sell=Boolean(t.falseBreakout||pat.haramiBear||(last.close<prev.low&&red(last)));return{available:true,buy:bias==='buy'&&buy,sell:bias==='sell'&&sell,reason:'تم فحص المصيدة/النموذج وتأكيد الإغلاق على الفاصل الصغير.',candles:cs.length}}
const check=(id,name,passed,weight,group,available=true,detail=null)=>({id,name,passed:Boolean(passed),weight,group,available,detail});
const score=checks=>Math.round(checks.reduce((s,x)=>s+(x.available&&x.passed?x.weight:0),0)/Math.max(1,checks.reduce((s,x)=>s+(x.available?x.weight:0),0))*100);

export function analyzeEod(input,config={}){
  const c={...EOD_CONFIG,...config},daily=normalizeCandles(Array.isArray(input)?input:input?.daily),intraday=Array.isArray(input)?[]:input?.intraday||[],warnings=[];
  if(daily.length<c.minDailyCandles)return{decision:'wait',score:0,mode:'insufficient-history',reason:`يلزم ${c.minDailyCandles} شمعة يومية؛ المتوفر ${daily.length}.`,warnings:['لم يصدر المحرك توصية كاملة من تاريخ غير كافٍ.'],checks:[],coverage:{daily:false,intraday:false}};
  const previousDaily=daily.at(-2),latestDaily=daily.at(-1),lastGapPct=previousDaily?.close?Math.abs(pct(latestDaily.open,previousDaily.close)):0;
  if(lastGapPct>25)return{decision:'wait',score:0,buyScore:0,sellScore:0,mode:'data-integrity-error',provisional:false,reason:'توقف التحليل لأن آخر شمعة لا تتسق مع السجل التاريخي المنسوب إلى هذا الرمز.',entry:null,stop:null,checks:[],warnings:[`فجوة غير منطقية ${lastGapPct.toFixed(1)}% بين آخر إغلاق والافتتاح التالي؛ يجب تصحيح ربط رمز السهم بملف الشموع.`],coverage:{courseConditions:false,daily:false,weekly:false,monthly:false,intraday:false},timeframes:{daily:daily.length,weekly:0,monthly:0,intraday:intraday.length}};
  const weekly=aggregate(daily,'week'),monthly=aggregate(daily,'month'),last=daily.at(-1),prev=daily.at(-2),dp=pivots(daily,c.pivotWindow),wp=pivots(weekly,c.pivotWindow),dailyTrend=trendOf(daily,c.pivotWindow),weeklyTrend=trendOf(weekly,c.pivotWindow),monthlyTrend=trendOf(monthly,c.pivotWindow),div=divergences(daily,c.rsiPeriod,c.pivotWindow),fib=fibonacci(weekly,last.close,c.fibTolerancePct,c.pivotWindow);
  const explosions=explosionEvents(daily,c),latestUp=explosions.filter(x=>x.direction==='up').at(-1),latestDown=explosions.filter(x=>x.direction==='down').at(-1),atBuyerExplosion=latestUp&&last.low<=latestUp.zoneHigh*(1+c.zoneTolerancePct/100)&&last.close>=latestUp.zoneLow,atSellerExplosion=latestDown&&last.high>=latestDown.zoneLow*(1-c.zoneTolerancePct/100)&&last.close<=latestDown.zoneHigh;
  const volumes=volumeCandles(daily,c),highVolume=volumes.at(-1)?.index===daily.length-1,traps=latestTrap(daily,dp,c),patterns=candlePatterns(daily),longTrap=largeContraryTrap(daily,weeklyTrend,c),volTrap=volumeTrap(daily,volumes,weeklyTrend,c),priorLow=wp.lows.length?weekly[wp.lows.at(-1)].low:null,priorHigh=wp.highs.length?weekly[wp.highs.at(-1)].high:null,nearWeeklyLow=near(last.close,priorLow,c.zoneTolerancePct),nearWeeklyHigh=near(last.close,priorHigh,c.zoneTolerancePct),bullishClose=green(last)&&(last.close>prev.high||patterns.haramiBull||traps.falseBreak||longTrap.buy||volTrap.buy),bearishClose=red(last)&&(last.close<prev.low||patterns.haramiBear||traps.falseBreakout||longTrap.sell||volTrap.sell),small=smallTimeframeEvidence(intraday,c,weeklyTrend==='down'?'sell':'buy');
  const buy=[check('trend-month-up','المسار الشهري صاعد',monthlyTrend==='up',10,'المسار'),check('trend-week-up','المسار الأسبوعي صاعد',weeklyTrend==='up',15,'المسار'),check('trend-day-up','المسار اليومي صاعد أو يصحح داخل صعود',dailyTrend==='up'||weeklyTrend==='up'&&dailyTrend==='neutral',5,'المسار'),check('buyer-zone','السعر في منطقة مشترين: قاع سابق أو بداية انفجار صاعد',nearWeeklyLow||atBuyerExplosion,12,'المناطق'),check('fib-buy','ارتداد قرب تصحيح فيبوناتشي في مسار صاعد',fib.near&&fib.direction==='up',7,'المناطق'),check('div-buy','دايفرجنس إيجابي عادي أو مخفي في موضع مناسب',div.bullishRegular||div.bullishHidden&&weeklyTrend==='up',8,'المؤشرات'),check('volume-buy','شمعة كميات أو مصيدة شمعة كميات لصالح الشراء',highVolume&&green(last)||volTrap.buy,7,'الكميات'),check('false-break','كسر وهمي لقاع ثم إغلاق أعلى منطقة الكسر',traps.falseBreak,10,'المصائد'),check('long-sell-reclaim','إلغاء شمعة بيع طويلة 3% بالإغلاق فوقها',longTrap.buy,7,'المصائد'),check('harami-buy','هارامي إيجابي مؤكد بالإغلاق فوق شمعة الأم',patterns.haramiBull,6,'النماذج'),check('explosion-buy','عودة إلى منطقة بداية انفجار سعري صاعد 6%',atBuyerExplosion,5,'الانفجار'),check('close-buy','تأكيد شرائي بالإغلاق لا بمجرد الذيل',bullishClose,8,'التأكيد'),check('small-buy','تأكيد شراء على فاصل الساعة أو أقل',small.buy,10,'الفاصل الصغير',small.available,small.reason)];
  const sell=[check('trend-month-down','المسار الشهري هابط',monthlyTrend==='down',10,'المسار'),check('trend-week-down','المسار الأسبوعي هابط',weeklyTrend==='down',15,'المسار'),check('trend-day-down','المسار اليومي هابط أو يصحح داخل هبوط',dailyTrend==='down'||weeklyTrend==='down'&&dailyTrend==='neutral',5,'المسار'),check('seller-zone','السعر في منطقة بائعين: قمة سابقة أو بداية انفجار هابط',nearWeeklyHigh||atSellerExplosion,12,'المناطق'),check('fib-sell','ارتداد قرب تصحيح فيبوناتشي في مسار هابط',fib.near&&fib.direction==='down',7,'المناطق'),check('div-sell','دايفرجنس سلبي عادي أو مخفي في موضع مناسب',div.bearishRegular||div.bearishHidden&&weeklyTrend==='down',8,'المؤشرات'),check('volume-sell','شمعة كميات أو مصيدة شمعة كميات لصالح البيع',highVolume&&red(last)||volTrap.sell,7,'الكميات'),check('false-breakout','اختراق وهمي لقمة ثم إغلاق أدنى منطقة الاختراق',traps.falseBreakout,10,'المصائد'),check('long-buy-break','إلغاء شمعة شراء طويلة 3% بالإغلاق تحتها',longTrap.sell,7,'المصائد'),check('harami-sell','هارامي سلبي مؤكد بالإغلاق تحت شمعة الأم',patterns.haramiBear,6,'النماذج'),check('explosion-sell','عودة إلى منطقة بداية انفجار سعري هابط 6%',atSellerExplosion,5,'الانفجار'),check('close-sell','تأكيد بيعي بالإغلاق لا بمجرد الذيل',bearishClose,8,'التأكيد'),check('small-sell','تأكيد بيع على فاصل الساعة أو أقل',small.sell,10,'الفاصل الصغير',small.available,small.reason)];
  const buyScore=score(buy),sellScore=score(sell),buyGate=(weeklyTrend==='up'||nearWeeklyLow||atBuyerExplosion)&&(bullishClose||small.buy),sellGate=(weeklyTrend==='down'||nearWeeklyHigh||atSellerExplosion)&&(bearishClose||small.sell);let decision='wait';if(buyGate&&buyScore>=c.minScore&&buyScore>sellScore)decision='buy';else if(sellGate&&sellScore>=c.minScore&&sellScore>buyScore)decision='sell';const checks=buyScore>=sellScore?buy:sell,finalScore=Math.max(buyScore,sellScore),side=decision==='wait'?(buyScore>=sellScore?'buy':'sell'):decision;
  let entry=decision==='buy'?Math.max(last.high,prev.high):decision==='sell'?Math.min(last.low,prev.low):null,stop=decision==='buy'?Math.min(last.low,traps.falseBreak?.level??last.low)*(1-c.stopBufferPct/100):decision==='sell'?Math.max(last.high,traps.falseBreakout?.level??last.high)*(1+c.stopBufferPct/100):null;const stopPct=entry&&stop?Math.abs(entry-stop)/entry*100:null;if(stopPct>c.maxStopPct){warnings.push(`مسافة وقف الخسارة ${stopPct.toFixed(1)}% بعيدة؛ تحولت النتيجة إلى انتظار.`);decision='wait';entry=stop=null}if(!small.available)warnings.push('لم تتوفر شموع فاصل الساعة أو أقل؛ أُنجز التحليل المسائي على الشهري والأسبوعي واليومي، ولم تُحتسب نقطة الفاصل الصغير في الدرجة.');
  return{decision,score:finalScore,buyScore,sellScore,mode:'full-course-eod',provisional:!small.available,reason:decision==='buy'?'اكتملت خلفية الشراء وتأكيد الإغلاق وفق شروط الدورة.':decision==='sell'?'اكتملت خلفية البيع وتأكيد الإغلاق وفق شروط الدورة.':'لم تجتمع الخلفية الفنية وتأكيد الإغلاق والدرجة المطلوبة.',entry,stop,trend:weeklyTrend,trends:{monthly:monthlyTrend,weekly:weeklyTrend,daily:dailyTrend},timeframes:{daily:daily.length,weekly:weekly.length,monthly:monthly.length,intraday:small.candles||0},coverage:{courseConditions:true,daily:true,weekly:true,monthly:true,intraday:small.available},signals:{explosionUp:Boolean(latestUp),explosionDown:Boolean(latestDown),atBuyerExplosion:Boolean(atBuyerExplosion),atSellerExplosion:Boolean(atSellerExplosion),highVolume,volumeTrapBuy:volTrap.buy,volumeTrapSell:volTrap.sell,falseBreak:Boolean(traps.falseBreak),falseBreakout:Boolean(traps.falseBreakout),longTrapBuy:longTrap.buy,longTrapSell:longTrap.sell,haramiBull:patterns.haramiBull,haramiBear:patterns.haramiBear,nearFib:fib.near,...div},checks,warnings,side};
}
